### ISSUE TITLE
commando: unknown parameter amount_msat

### ISSUE THREAD

**Issue by darthginger** [nbd-wtf/satdress#33]
Im trying out the new commando backend. Im using cln 0.11.2.
I made the rune with `lightning-cli commando-rune restrictions='["method=invoice"]'`
But i get this error after hitting submit:
`couldn't make an invoice with the given data: unknown parameter: amount_msat, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters.`

**Comment by fiatjaf** [comment]
You must have `allow-deprecated-apis=false` in your CLN `config` file.

We chose to not support the old APIs because they are old and will be replaced anyway. And commando is only available for new nodes so that made sense.

**Comment by darthginger** [comment]
I put that config line in, didn't change anything.

**Comment by fiatjaf** [comment]
Sorry, you'll need the latest `master`. Or wait for the next release, and throw away the Python plugin. The current `master` has a built-in Commando.
