### ISSUE TITLE
Feature request:  commando: support rune rate limiting

### ISSUE THREAD

**Issue by darthginger** [nbd-wtf/satdress#34]
Im using cln 0.11.2
When i craft the rune like this: `lightning-cli commando-rune restrictions='["method=invoice","rate=30"]'
`
I get an error after hitting submit:
`couldn't make an invoice with the given data: Not authorized: rate: is missing`

Without the rate part i get a different unrelated error as seen in #33 which makes me think satdress doesn't support rate limiting.

**Comment by fiatjaf** [comment]
Satdress knows nothing about rate limits, it just sends the runes. If that is a bug then it is a bug on the CLN side.

**Comment by fiatjaf** [comment]
Wait, are you using CLN compiled from `master`? Or are you using the legacy Python Commando plugin?

**Comment by darthginger** [comment]
Im using the release version 0.11.2 with the python commando plugin.

**Comment by fiatjaf** [comment]
That won't work, you need the latest `master`.
