### ISSUE TITLE
Yunohost satdress app package

### ISSUE THREAD

**Issue by BitromNO** [nbd-wtf/satdress#35]
Hi! I'm running a Yunohost server with a Norwegian bitcoin forum [bitrom forum](https://bitrom.no)
is it possible to make a app package to install in the server?

**Comment by fiatjaf** [comment]
It is definitely possible from what I'm reading at https://yunohost.org/en/packaging_apps
But from what I'm reading it is also a very time-consuming task, so we'll need someone to step up and show us the way.

I imagine it should be pretty simple for people who are used to this Yunohost magic.

**Comment by navanchauhan** [comment]
Package development has started at https://github.com/YunoHost-Apps/satdress_ynh 

For now, it can be installed by running `sudo yunohost install https://github.com/YunoHost-Apps/tree/testing` via ssh while I squash some bugs with the package

Feel free to close this issue

**Comment by fiatjaf** [comment]
Amazing!

**Comment by BitromNO** [comment]
Thank you so much! tested the app and it works! :)
